export const Films = [
    {
        id: 1, 
        img: "film/chuot-dau-bep-ratatouille.jpg",
        title: "Chuột đầu bếp", 
        year: "2007", 
        nation: "USA", 
        video:"https://youtu.be/NgsQ8mVkN8w",
        info: "Chú chuột đầu bếp là bộ phim hoạt hình vui nhộn, dễ thương đủ để khiến trẻ em thích thú, và cũng đủ tinh tế, triết lý, sâu sắc và đậm tính nhân văn để người lớn phải suy ngẫm sau khi xem. Đây là một bộ phim dành cho trẻ em và cả người lớn. Phim kể về câu chuyện của Remy, một chú chuột có biệt tài ngửi mùi, muốn trở thành đầu bếp nhưng đã gặp phải sự ngăn cản từ gia đình và loài người. Gia đình cậu đã sử dụng biệt tài ngửi mùi để giúp họ hàng nhà chuột phân biệt thức ăn có đánh bả và thức ăn an toàn. Tuy nhiên, mang trong mình ước mơ mãnh liệt trở thành 1 đầu bếp lừng danh ở Paris, chú chuột Remy đã vượt qua mọi gian khổ, khó khăn và thử thách để theo đuổi niềm đam mê, khao khát nghề nghiệp của mình để thực hiện ước mơ của mình và trở thành một đầu bếp trứ danh."},
    {
        id: 2, 
        img: "film/cong-chua-toc-may-tangled.jpg", 
        title: "Công chúa tóc mây", 
        year: "2011", 
        nation: "USA", 
        video:"https://youtu.be/ycoY201RTRo",
        info: "Người đẹp tóc mây – Tangled là bộ phim hoạt hình thứ 50 của hãng hoạt hình Walt Disney. Lấy ý tưởng từ câu truyện cổ tích Rapunzel của anh em Grimm về một cô gái có mái tóc dài thướt tha, sống trên một tòa tháp không có đường ra vào ngoài chiếc cửa sổ trên cao, Rapunzel được xem như là nàng công chúa đẹp và được yêu thích nhất của Disney, khá dịu dàng và cũng rất nóng tính, cung hoàng đạo của Rapunzel là Thần Nông (Thiên Yết, Bọ Cạp) kế đến là Aurora trong (The Sleeping Beauty). Đạo diễn cho bộ phim này là Nathan Greno và Byron Howard, từng đạo diễn cho bộ phim Tia Chớp. Người đẹp tóc mây là bộ phim có kinh phí cao thứ hai trong lịch sử Hollywood, và cũng là bộ phim hoạt hình có kinh phí sản xuất cao nhất."},
    {
        id: 3, 
        img: "film/finding-nemo.jpg", 
        title: "Đi Tìm Nemo", 
        year: "2003", 
        nation: "USA", 
        video:"https://youtu.be/9oQ628Seb9w",
        info: "Bộ phim Finding Nemo kể câu chuyện về chuyến đi đầy khó khăn, gian khổ của chú hề cá Marlin. Đó là hành trình đi tìm đứa con trai của mình là Nemo. Mở đầu đoạn phim cuộc sống ở Vỉa San Hô ẩn chứa những nguy hiểm và cạm bẫy rình rập. Chính vì vậy, Marlin luôn dặn dò, bảo ban con trai mình rằng hãy cẩn thận nơi đây.Một thời gian sau, Nemo bắt đầu đi học ở trường. Nhưng thường cảm thấy xấu hổ bởi sự quan tâm quá mức của Marlin. Với bản tính ham chơi và muốn chứng tỏ rằng sự quan tâm và lo lắng vô căn cứ. Nemo đã bơi ra ngoài để tận hưởng dòng nước và trên đường bơi. Cậu bị một người thợ lặn bắt. Nhìn thấy con mình bị bắt, Marlin cố gắng bơi theo con tàu nhưng không kịp. Và rồi chuyến hành trình tìm đứa con bắt đầu từ đây." },
    {
        id: 4, 
        img: "film/frozen-2-nu-hoang-bang-gia.jpg", 
        title: "Nữ hoàng băng giá", 
        year: "2013", 
        nation: "USA", 
        video:"https://youtu.be/Zi4LMpSDccc",
        info: "Nữ hoàng băng giá (còn gọi là Băng giá, tiếng Anh: Frozen) là phim điện ảnh nhạc kịch kỳ ảo sử dụng công nghệ hoạt hình máy tính của Mỹ do Walt Disney Animation Studios sản xuất và Walt Disney Pictures phát hành vào năm 2013. Đây là bộ phim hoạt hình chiếu rạp thứ 53 trong series Walt Disney Animated Classics. Lấy cảm hứng từ câu chuyện cổ tích Bà chúa Tuyết của nhà văn Hans Christian Andersen, bộ phim kể câu chuyện về một nàng công chúa dũng cảm lên đường dấn thân vào một cuộc hành trình gian khó với một anh chàng miền núi cường tráng, dễ rung động nhưng ban đầu hơi thô lỗ, cùng chú tuần lộc trung thành của mình và một chàng người tuyết vui nhộn tình cờ gặp để đi tìm người chị gái đang phải sống một mình trên núi, một nữ hoàng sở hữu sức mạnh tạo ra băng giá đã vô tình khiến cả vương quốc chìm trong mùa đông vĩnh cửu." },
    {
        id: 5, 
        img: "film/spirited-away.jpg", 
        title: "Vùng Đất Linh Hồn", 
        year: "2001", 
        nation: "JAPAN",
        video:"https://youtu.be/ByXuk9QqQkk", 
        info: "Vùng đất linh hồn “Spirited Away” là một trong những siêu phẩm xuất sắc nhất của hãng phim hoạt hình Ghibli Nhật Bản. Nó kể về câu chuyện một cô bé 10 tuổi tên là Chihiro đi lạc vào thế giới của những linh hồn. Ở đây cô bé phải tìm cách giải cứu bố mẹ mình khỏi số phận bị biến thành những con lợn, đồng thời cô cũng phải tự cứu mình khỏi thân phận nô lệ đã bị xoá mất danh tính bởi bà phù thuỷ Yubaba." },
    {
        id: 6, 
        img: "film/the-incredibles.jpg", 
        title: "Gia đình siêu nhân", 
        year: "2004", 
        nation: "USA", 
        video:"https://youtu.be/-UaGUdNJdRQ",
        info: "Gia đình siêu nhân (tựa tiếng Anh: The Incredibles) là một bộ phim hoạt hình máy tính (3D) thuộc thể loại siêu anh hùng được Pixar Animation Studios sản xuất và hãng Walt Disney Pictures phát hành. Phim được Brad Bird, một cựu đạo diễn và cố vấn điều hành trong chương trình The Simpsons, viết kịch bản và đạo diễn. Bộ phim có sự tham gia của các diễn viên lồng tiếng Holly Hunter, Craig T. Nelson, Sarah Vowell, Spencer Fox, Jason Lee, Samuel L. Jackson và Elizabeth Peña" },
    {
        id: 7, 
        img: "film/the-lion-king.jpg", 
        title: "Vua sư tử", 
        year: "1994", 
        nation: "USA", 
        video:"https://youtu.be/lFzVJEksoDY",
        info: "The Lion King kể về chú sư tử Simba – ra đời trong sự yêu thương của cha mẹ và muôn loài cũng như được lựa chọn để trở thành chúa sơn lâm tiếp theo. Tuy nhiên, dưới âm mưu độc ác của người chú Scar, Simba mất hết tất cả và phải bỏ đi biệt tích. Cậu dần lớn lên và quên rằng mình là ai, chỉ biết sống một cuộc sống tự do tự tại, vô lo vô nghĩ. Tuy nhiên, định mệnh đã lựa chọn cậu là nhà vua, buộc Simba phải trở về để đối mặt với quá khứ và ách đô hộ của người chú lên vương quốc của mình." },
    {
        id: 8, 
        img: "film/toy-story.jpg", 
        title: "Câu chuyện đồ chơi", 
        year: "1995", 
        nation: "USA", 
        video:"https://youtu.be/v-PjgYDrg70",
        info: "Câu chuyện đồ chơi (tên tiếng Anh: Toy Story) là bộ phim hoạt hình máy tính của Mỹ ra mắt vào năm 1995 do xưởng phim hoạt hình Pixar sản xuất và Walt Disney Pictures phát hành. Đây là bộ phim hoạt hình dài đầu tiên của Pixar sử dụng công nghệ 3D và là bộ phim hoạt hình dài được sản xuất bằng máy tính đầu tiên trong lịch sử điện ảnh. Woody là một chàng cao bồi đồ chơi và là đội trưởng trong số những đồ chơi của cậu bé Andy Davis. Do gia đình sẽ chuyển đi một tuần trước ngày sinh nhật của Andy nên cậu được tổ chức một bữa tiệc sinh nhật sớm cùng với bạn bè của mình. Để khám phá những món quà mới của Andy, các món đồ chơi thực hiện một nhiệm vụ do thám khi bữa tiệc diễn ra. Andy được tặng một mô hình cảnh sát vũ trụ Buzz Lightyear với những tính năng ấn tượng và Buzz nhanh chóng thay thế Woody để trở thành đồ chơi yêu thích của Andy. Woody trở nên ghen tức, đặc biệt là khi Buzz Lightyear chiếm được cảm tình từ các món đồ chơi khác. Mặc dù vậy, Buzz lại nghĩ mình là một cảnh sát vũ trụ thực thụ đang trong quá trình thực hiện nhiệm vụ để trở về hành tinh của mình." },
    {
        id: 9, 
        img: "film/up.jpg", 
        title: "Vút bay", 
        year: "2009", 
        nation: "USA", 
        video:"https://youtu.be/HWEW_qTLSEE",
        info: "Up là câu chuyện của ông lão Carl, sống một mình trong ngôi nhà gỗ sau khi vợ ông (bà Ellie) qua đời. Nhân vật chính còn lại là cậu bé tình nguyện viên Russell đang tìm kiếm một công việc giúp đỡ người cao tuổi để nhận được huy hiệu giúp đỡ người cao tuổi nhằm hoàn thành bộ sưu tập huy hiệu của mình. Ông lão Carl thấy cậu quá phiền phức nên đã nói dối để cậu đi tìm con chìm dẽ giun trong vườn để không làm phiến ông nữa.Ông cũng quá mệt mỏi với những gì diễn ra tại công trường xây dựng xung quanh nhà mình. Những nhà thầu xây dựng yêu cầu ông di rời để chúng có thể tiếp tục việc xây dựng tòa nhà cao tầng. Ông Carl không muốn rời xa ngôi nhà với bao kỷ niệm của mình nên quyết định thực hiện một chuyến phiêu lưu bằng bóng bay đến Nam Mỹ – thực hiện ước mơ đến “Thác nước Thiên đường” mà hai vợ chồng ông đã ấp ủ từ khi còn nhỏ." },
]